--ATENÇÃO: este script deve ser executado após a excução do script tab.sql e com a sessão aberta como usuário a2p_user
--para os objetos:
GRANT ALL ON TABLE a2p.audit TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.artefato TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.grupo TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.grupo_permissao TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.perfil TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.permissao TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.repara_senha TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.sistema TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.usuario TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.usuario_grupo TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.usuario_perfil TO GROUP a2p WITH GRANT OPTION;

--SEQUENCE
GRANT ALL ON TABLE a2p.audit_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.usuario_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.sistema_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.perfil_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.artefato_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.grupo_id_seq TO GROUP a2p WITH GRANT OPTION;
GRANT ALL ON TABLE a2p.permissao_id_seq TO GROUP a2p WITH GRANT OPTION;


--VIEWS
GRANT ALL ON TABLE a2p.vw_municipio TO GROUP a2p WITH GRANT OPTION;
